###
POST http://localhost:8081/register-node?
    host=1.2.3.4&
    port=8080&
    name=SoyLegenda

###
POST http://localhost:8089/play
Content-Type: application/json

{
"hola": true
}

###
POST http://localhost:8089/play
Content-Type: text/plain

{asdsadadad
adasdad"hola": true
}

###
POST http://localhost:8080/play
Content-Type: application/xml

<a>
    <b>asdada</b>
</a>
